apiVersion: v1
kind: Pod
metadata: 
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: cagatayerdiz/multi-client
      ports:
        - containerPort: 3000